orbs:
  node: circleci/node@4.0.0

version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node@4.0.0
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - run:
          name: build
          command: node/build
      - run:
          name: jFrog CLI のインストール
          command: curl -fL https://getcli.jfrog.io | sh
      - run:
          name: Artifactory へのプッシュ
          command: |
            ./jfrog rt config --url $ARTIFACTORY_URL --user $ARTIFACTORY_USER --apikey $ARTIFACTORY_APIKEY --interactive=false
            ./jfrog rt u <path/to/artifact> <artifactory_repo_name> --build-name=<name_you_give_to_build> --build-number=$CIRCLE_BUILD_NUM
            ./jfrog rt bce <name_you_give_to_build> $CIRCLE_BUILD_NUM
            ./jfrog rt bp <name_you_give_to_build> $CIRCLE_BUILD_NUM 

workflows:
  app-tests:
    jobs:
      - node/test
  builds:
    jobs:
      - build
